export type Season =
  | 'light_spring'
  | 'true_spring'
  | 'warm_spring'
  | 'light_summer'
  | 'true_summer'
  | 'soft_summer'
  | 'soft_autumn'
  | 'true_autumn'
  | 'dark_autumn'
  | 'deep_winter'
  | 'true_winter'
  | 'cool_winter';

export type Subtone =
  // SPRING
  | 'da_hong_nhe'
  | 'da_vang_sang'
  | 'da_be_sang'
  | 'da_olive_nhe'
  | 'da_trung_tinh_mit'
  | 'vang_ong'
  | 'vang_kem'
  | 'vang_dao'
  | 'vang_ngam'
  | 'vang_be'
  | 'vang_sang'
  | 'vang_trung_tinh'
  // SUMMER
  | 'hong_lanh'
  | 'be_lanh'
  | 'trang_xam'
  | 'hong_nhe_trung_tinh'
  | 'trang_xanh_lanh'
  | 'hong_lanh_sang'
  | 'hong_be_tram'
  | 'trung_tinh_nghi_lanh'
  | 'be_xam_lanh'
  | 'hong_xam_nhe'
  | 'trung_tinh_xam'
  // AUTUMN
  | 'be_vang_nhe'
  | 'be_hong_nguoi'
  | 'vang_xam'
  | 'trung_tinh_am'
  | 'ngam_vang_mem'
  | 'nau_sang_am'
  | 'vang_ong_am'
  | 'be_vang_sang'
  | 'vang_nau_ngam'
  | 'be_ngam_ach'
  | 'trung_tinh_sam_am'
  // WINTER
  | 'trang_hong_lanh'
  | 'trang_xam_sang'
  | 'ngam_lanh'
  | 'trung_tinh_lanh'
  | 'trang_xam_lanh';

export type DominantFeature =
  // Common
  | 'low_contrast'
  | 'medium_contrast'
  // SPRING
  | 'mat_sang_noi_bat'
  | 'toc_sang_noi_bat'
  | 'da_ruc_sang'
  | 'mat_xanh_la'
  | 'toc_vang_cam'
  | 'da_noi_bat'
  // SUMMER
  | 'mat_sang_xam'
  | 'toc_xam_tro'
  | 'do_tuong_phan_vua'
  | 'mat_xam_nhat'
  | 'toc_nau_tro'
  | 'mat_xam_tro'
  | 'toc_nau_xam'
  // AUTUMN
  | 'mat_nau_rong'
  | 'toc_nau_reu'
  | 'mat_nau_reu'
  | 'toc_nau_cam'
  | 'do_tuong_phan_trung'
  | 'do_tuong_phan_trung_binh'
  | 'toc_nau_sam'
  | 'mat_nau_sau'
  | 'do_tuong_phan_cao'
  | 'tone_dong_deu'
  // WINTER
  | 'toc_den_dam'
  | 'mat_sau_ruc'
  | 'tuong_phan_cao'
  | 'tong_toi_dong_deu'
  | 'toc_den_xanh'
  | 'mat_sang_lanh'
  | 'tong_sang_ro_net'
  | 'mat_xanh_lanh'
  | 'toc_den_lanh'
  | 'tong_lanh_ro_net';

export type Style = {
  id: number;
  slug: string;
  name: string;
};
